#!/usr/bin/env python3
"""
Firewall Rules Automation Manager
Generates, audits, and documents firewall rules from YAML policy definitions.

Author: Jack Ke Jiang
"""

import yaml
import argparse
import sys
import ipaddress
from datetime import datetime
from pathlib import Path


def load_policies(policy_file="policies.yaml"):
    """Load firewall policies from YAML file."""
    with open(policy_file, "r") as f:
        return yaml.safe_load(f)


def ip_to_wildcard(cidr):
    """Convert CIDR notation to Cisco wildcard mask format."""
    if cidr == "any":
        return "any"
    try:
        network = ipaddress.ip_network(cidr, strict=False)
        hostmask = str(network.hostmask)
        return f"{network.network_address} {hostmask}"
    except ValueError:
        return cidr


def ip_to_iptables(cidr):
    """Format IP for iptables rules."""
    if cidr == "any":
        return ""
    return cidr


def generate_cisco_acl(policies):
    """Generate Cisco ACL rules from policies."""
    lines = []
    lines.append("! =============================================================")
    lines.append("! Firewall Rules - Generated by fw_manager.py")
    lines.append(f"! Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    lines.append("! Source: policies.yaml")
    lines.append("! =============================================================")
    lines.append("")

    for policy in policies.get("policies", []):
        name = policy.get("name", "Unnamed")
        description = policy.get("description", "")
        source = policy.get("source", "any")
        destination = policy.get("destination", "any")
        ports = policy.get("ports", [])
        protocol = policy.get("protocol", "ip")
        action = policy.get("action", "deny")
        zone_from = policy.get("zone_from", "any")
        zone_to = policy.get("zone_to", "any")
        justification = policy.get("business_justification", "Not documented")

        # ACL name based on zones
        acl_name = f"{zone_from}_{zone_to}".upper().replace(" ", "_")

        lines.append(f"! --- {name} ---")
        if description:
            lines.append(f"! {description}")
        lines.append(f"! Business justification: {justification}")

        src_formatted = ip_to_wildcard(source)
        dst_formatted = ip_to_wildcard(destination)

        # Handle "host" notation for /32
        if source != "any":
            try:
                net = ipaddress.ip_network(source, strict=False)
                if net.prefixlen == 32:
                    src_formatted = f"host {net.network_address}"
            except ValueError:
                pass

        if destination != "any":
            try:
                net = ipaddress.ip_network(destination, strict=False)
                if net.prefixlen == 32:
                    dst_formatted = f"host {net.network_address}"
            except ValueError:
                pass

        # Generate a rule for each port
        for port in ports:
            log_suffix = " log" if action == "deny" else ""
            lines.append(
                f"access-list {acl_name} {action} {protocol} "
                f"{src_formatted} {dst_formatted} eq {port}{log_suffix}"
            )

        lines.append("")

    return "\n".join(lines)


def generate_iptables(policies):
    """Generate iptables rules from policies."""
    lines = []
    lines.append("#!/bin/bash")
    lines.append("# =============================================================")
    lines.append("# Firewall Rules - Generated by fw_manager.py")
    lines.append(f"# Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    lines.append("# Source: policies.yaml")
    lines.append("# =============================================================")
    lines.append("")
    lines.append("# Flush existing rules")
    lines.append("iptables -F")
    lines.append("iptables -X")
    lines.append("")
    lines.append("# Default policies - deny all")
    lines.append("iptables -P INPUT DROP")
    lines.append("iptables -P FORWARD DROP")
    lines.append("iptables -P OUTPUT DROP")
    lines.append("")
    lines.append("# Allow established connections")
    lines.append("iptables -A INPUT -m state --state ESTABLISHED,RELATED -j ACCEPT")
    lines.append("iptables -A OUTPUT -m state --state ESTABLISHED,RELATED -j ACCEPT")
    lines.append("")

    for policy in policies.get("policies", []):
        name = policy.get("name", "Unnamed")
        source = policy.get("source", "any")
        destination = policy.get("destination", "any")
        ports = policy.get("ports", [])
        protocol = policy.get("protocol", "tcp")
        action = policy.get("action", "deny")
        justification = policy.get("business_justification", "")

        target = "ACCEPT" if action == "permit" else "DROP"

        lines.append(f"# {name}")
        if justification:
            lines.append(f"# Justification: {justification}")

        for port in ports:
            cmd = "iptables -A FORWARD"
            if source != "any":
                cmd += f" -s {source}"
            if destination != "any":
                cmd += f" -d {destination}"
            cmd += f" -p {protocol} --dport {port} -j {target}"
            lines.append(cmd)

        lines.append("")

    return "\n".join(lines)


def audit_rules(rules_text):
    """
    Audit a set of rules for common issues.
    Analyzes for redundancies, shadows, and missing documentation.
    """
    lines = rules_text.strip().split("\n")
    rules = []
    issues = []

    # Parse rules (simplified Cisco ACL format)
    for i, line in enumerate(lines, 1):
        line = line.strip()
        if line.startswith("access-list") or line.startswith("iptables"):
            rules.append({"line_num": i, "text": line})

    # Check for potential shadowing (simplified check)
    deny_rules = [r for r in rules if "deny" in r["text"] or "DROP" in r["text"]]
    permit_rules = [r for r in rules if "permit" in r["text"] or "ACCEPT" in r["text"]]

    for permit in permit_rules:
        for deny in deny_rules:
            if deny["line_num"] < permit["line_num"]:
                # Check if deny rule might shadow the permit rule
                if "any" in deny["text"] and "any" in deny["text"]:
                    issues.append({
                        "severity": "CRITICAL",
                        "message": f"Rule {permit['line_num']} may be shadowed by broader deny Rule {deny['line_num']}",
                        "rule": permit["text"],
                        "shadowed_by": deny["text"]
                    })

    # Check for rules without comments/justification
    prev_was_comment = False
    for rule in rules:
        if not prev_was_comment:
            issues.append({
                "severity": "INFO",
                "message": f"Rule {rule['line_num']} has no preceding comment/justification",
                "rule": rule["text"]
            })
        # Reset for next iteration
        line_above = rules_text.split("\n")[rule["line_num"] - 2] if rule["line_num"] > 1 else ""
        prev_was_comment = line_above.strip().startswith(("!", "#"))

    return issues


def generate_compliance_report(policies):
    """Generate a compliance report mapping business requirements to rules."""
    lines = []
    lines.append("=" * 70)
    lines.append("  FIREWALL COMPLIANCE REPORT")
    lines.append(f"  Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    lines.append("=" * 70)
    lines.append("")
    lines.append(f"  {'#':<4} {'Policy Name':<30} {'Action':<8} {'Justification'}")
    lines.append(f"  {'-'*4} {'-'*30} {'-'*8} {'-'*40}")

    for i, policy in enumerate(policies.get("policies", []), 1):
        name = policy.get("name", "Unnamed")[:30]
        action = policy.get("action", "N/A")
        justification = policy.get("business_justification", "NOT DOCUMENTED")

        lines.append(f"  {i:<4} {name:<30} {action:<8} {justification}")

    lines.append("")
    lines.append("=" * 70)

    # Summary
    total = len(policies.get("policies", []))
    documented = sum(1 for p in policies.get("policies", []) if p.get("business_justification"))
    undocumented = total - documented

    lines.append(f"  Total policies: {total}")
    lines.append(f"  Documented: {documented}")
    lines.append(f"  Missing justification: {undocumented}")
    if undocumented > 0:
        lines.append(f"  [ACTION REQUIRED] {undocumented} policies need business justification")
    else:
        lines.append("  [COMPLIANT] All policies have business justification documented")
    lines.append("=" * 70)

    return "\n".join(lines)


def log_change(policy_name, change_type, details):
    """Log a rule change for audit trail."""
    log_file = "changelog.csv"
    import csv

    file_exists = Path(log_file).exists()
    with open(log_file, "a", newline="") as f:
        writer = csv.writer(f)
        if not file_exists:
            writer.writerow(["timestamp", "policy", "change_type", "details", "author"])
        writer.writerow([
            datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
            policy_name,
            change_type,
            details,
            "jack.jiang"  # In production, pull from auth context
        ])


def main():
    parser = argparse.ArgumentParser(description="Firewall Rules Automation Manager")
    subparsers = parser.add_subparsers(dest="command")

    # Generate command
    gen_parser = subparsers.add_parser("generate", help="Generate firewall rules")
    gen_parser.add_argument("--format", choices=["cisco", "iptables"], default="cisco")
    gen_parser.add_argument("--policies", default="policies.yaml")
    gen_parser.add_argument("--output", default=None)

    # Audit command
    audit_parser = subparsers.add_parser("audit", help="Audit existing rules")
    audit_parser.add_argument("--input", required=True, help="File with current rules")

    # Report command
    report_parser = subparsers.add_parser("report", help="Generate compliance report")
    report_parser.add_argument("--policies", default="policies.yaml")
    report_parser.add_argument("--output", default=None)

    # Changelog command
    subparsers.add_parser("changelog", help="Show change log")

    args = parser.parse_args()

    if args.command == "generate":
        policies = load_policies(args.policies)

        if args.format == "cisco":
            output = generate_cisco_acl(policies)
        else:
            output = generate_iptables(policies)

        if args.output:
            with open(args.output, "w") as f:
                f.write(output)
            print(f"Rules written to {args.output}")
        else:
            print(output)

        # Log the generation
        log_change("ALL", "GENERATE", f"Generated {args.format} rules from {args.policies}")

    elif args.command == "audit":
        with open(args.input, "r") as f:
            rules_text = f.read()

        issues = audit_rules(rules_text)

        print("=== FIREWALL RULE AUDIT REPORT ===\n")
        if issues:
            for issue in issues:
                print(f"[{issue['severity']}] {issue['message']}")
                print(f"  Rule: {issue['rule']}")
                if "shadowed_by" in issue:
                    print(f"  Shadowed by: {issue['shadowed_by']}")
                print()

            critical = sum(1 for i in issues if i["severity"] == "CRITICAL")
            warning = sum(1 for i in issues if i["severity"] == "WARNING")
            info = sum(1 for i in issues if i["severity"] == "INFO")
            print(f"Summary: {len(issues)} issues ({critical} critical, {warning} warning, {info} info)")
        else:
            print("No issues found. All rules look good.")

    elif args.command == "report":
        policies = load_policies(args.policies)
        output = generate_compliance_report(policies)

        if args.output:
            with open(args.output, "w") as f:
                f.write(output)
            print(f"Report written to {args.output}")
        else:
            print(output)

    elif args.command == "changelog":
        log_file = "changelog.csv"
        if not Path(log_file).exists():
            print("No changes logged yet.")
            return
        with open(log_file, "r") as f:
            print(f.read())

    else:
        parser.print_help()


if __name__ == "__main__":
    main()
